---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# bases:
#   - ../../base
# patchesStrategicMerge:
#   - namespace.yaml
#   - configmap.yaml
#   - job.yaml
#   - crb.yaml

resources:
  - namespace.yaml
  - configmap.yaml
  # - job.yaml
  - crb.yaml