apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: filenet-test
  namespace: filenet-test
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - filenet-test