apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-one-shot
  namespace: apollo-one-shot
data:
  variables.yml: |
    # Always set these parameters to your values #

    ## Entitlement key from the IBM Container software library. 
    ## (https://myibm.ibm.com/products-services/containerlibrary)  
    icr_password: TODO_ICR_PASSWORD

    ## Name of the StorageClass used for all PVCs which must be already present in your OpenShift. 
    ## Must be RWX and Fast.
    ## For ROKS this class could be ibmc-file-gold-gid (But strongly discouraged due to slow PVC binding)
    ## For NFS based class this could be managed-nfs-storage
    ## For ODF (OCS) based class (e.g. on ARO or ROSA) this could be ocs-storagecluster-cephfs
    storage_class_name: ocs-storagecluster-cephfs

    ## Options are OCP and ROKS (ROKS is specific to managed OpenShift on IBM Cloud)
    ## OCP option also applies to other managed OpenShifts ( like ARO, ROSA, etc. )
    deployment_platform: OCP

    ## In the Platform, multiple users and keystores and other encrypted entries need a password.
    ## To make working with the Platform easier all places which require a password share the same one from this variable.
    ## Make this password strong to ensure that no one from the outside world can login to your Platform.
    ## Password must be alphanumeric (upper and lower case; no special characters allowed).
    universal_password: Passw0rd


    # Always review these parameters for changes

    ## Set to false if you don't want to install (or remove) Process Mining
    pm_enabled: true

    ## Set to false if you don't want to install (or remove) Asset Repo
    asset_repo_enabled: true

    ## Set to false if you don't want to install (or remove) RPA
    rpa_enabled: true

    ## Set to false if you don't want to install (or remove) AKHQ
    akhq_enabled: true

    ## Set to false if you don't want to install (or remove) Cerebro
    cerebro_enabled: true

    ## Set to false if you don't want to install (or remove) DB2 Management Console
    db2mc_enabled: true

    ## Set to false if you don't want to install (or remove) Roundcube
    roundcube_enabled: true

    ## Set to false if you don't want to install (or remove) Mongo Express
    mongo_express_enabled: true